Test: circleci config; testing IMAGE_NAME variable

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,21 +8,21 @@ jobs:
       - run:
           name: Validate required environment variables were set in CircleCI project configuration
           command: |
-            [ -n "$AWS_ACCESS_KEY_ID" ] || (echo "ERROR: AWS_ACCESS_KEY_ID was not set in your CircleCI profile environment variables!" && exit 1)
-            [ -n "$AWS_SECRET_ACCESS_KEY" ] || (echo "ERROR: AWS_SECRET_ACCESS_KEY was not set in your CircleCI profile environment variables!" && exit 1)
-            [ -n "$AWS_REGION" ] || (echo "ERROR: AWS_REGION was not set in your CircleCI profile environment variables!" && exit 1)
+            [ -n "$AWS_ACCESS_KEY_ID" ] || (echo "ERROR: AWS_ACCESS_KEY_ID was not set in your CircleCI profile environment variables" && exit 1)
+            [ -n "$AWS_SECRET_ACCESS_KEY" ] || (echo "ERROR: AWS_SECRET_ACCESS_KEY was not set in your CircleCI profile environment variables" && exit 1)
+            [ -n "$AWS_REGION" ] || (echo "ERROR: AWS_REGION was not set in your CircleCI profile environment variables" && exit 1)
       - checkout
-      # - run:
-      #     name: Install Terraform CLI
-      #     command: |
-      #       sudo apt-get update
-      #       sudo apt-get install -y gnupg software-properties-common
-      #       wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
-      #       gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
-      #       echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
-      #       sudo apt update
-      #       sudo apt-get -y install terraform
-      #       terraform --version
+      - run:
+          name: Install Terraform CLI
+          command: |
+            sudo apt-get update
+            sudo apt-get install -y gnupg software-properties-common
+            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
+            gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
+            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
+            sudo apt update
+            sudo apt-get -y install terraform
+            terraform --version
       - run:
           name: Install AWS CLI and configure
           command: |
@@ -48,6 +48,7 @@ jobs:
             echo AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
             echo AWS_ECR_REPO_URL=$AWS_ECR_REPO_URL
             echo IMAGE_NAME=$IMAGE_NAME
+            [ -n "$IMAGE_NAME" ] || (echo "ERROR: IMAGE_NAME was not set correctly" && exit 1)
       # - run:
       #     name: Apply Terraform service architecture
       #     command: |
